
SRC =ft_check_operator.c ft_strcmp.c
SRCB =ft_strcmp.c ft_sqrt_bonus.c\
	ft_check_operator_bonus.c ft_power_bonus.c\

all :
	@gcc calculator.c $(SRC)
	@./a.out

bonus :
	@gcc calculator_bonus.c $(SRCB)
	@./a.out

clean :
	@rm a.out
	@clear
